### ISSUE TITLE
issuingAuthority for the identifier

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Person-Vocabulary#14]
I think it could be worth considering to rename the issuingAuthority in issuingAuthorityName that clearly distinguish it from the URI. 

However, there is a general question here: why do not we use the concept defined in CPOV (or Legal Entity) for the authority, thus creating a link in this case with the two vocabularies?

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, there were no objections regarding this proposition. There was also a suggestion to change the datatype from literal to text, in order to be consistent. 

There was no consensus however on directly linking it to a class (e.g. org:Organization, cpov:PublicOrganisation, etc.). It was said that this should be part of an Application Profile.

There was a counterargument stating that, if the range is not restricted, there is then a need for defining a more general approach for CPV and CBV covering Agent or Organisation and which one can be used in the Core Vocabularies according to the specific use cases.

**Comment by EmidioStani** [comment]
The issuingAuthority property has been renamed in issuingAuthorityName with range Text, see: https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/#Identifier
