### ISSUE TITLE
Need to conflate CPV, CPOV and CBV into a CAGV

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/Core-Person-Vocabulary#6]
In many different projects for the EU Commission and MS we have gone through the  experience of not knowing exactly what vocabularies and entities (classes and properties to reuse when the time comes to deal with natural persons, businesses, public authorities and roles (or not finding basic entities that should be in one or in another of these vocabularies, e.g. ContactPoint, Address).

One suggestion coming namely from inside the European Commission is that all these vocabularies could be merged into one single vocabulary named "Core Agent Vocabulary", abbreviated CAGV (not [CAV](https://joinup.ec.europa.eu/solution/core-assessment-vocabulary-cav), as this vocabulary does also exist in ISA2).

This Core Agent Vocabulary (CAGV) would reuse (namely extend) the generic FOAF, W3C, LCN, etc. ontologies. 

The main benefit of the CAGV would consist in having "one single reference vocabulary" where everything related to possible agents and roles played by agents are there, in a coherent and consistent way, so no more doubts arouse about whether to use Organization, RegisteredOrganization or LegalEntity, for example. 

We'd like to "throw" an initial proposal to start the discussion asap. Any reaction will be appreciated:

![image](https://user-images.githubusercontent.com/16134316/79261973-db6d8680-7e90-11ea-9a23-ef61b2c1844d.png)

**Comment by paulakeen** [comment]
refined proposal:

![image](https://user-images.githubusercontent.com/16134316/79373537-015d5e80-7f57-11ea-9157-6641391e7deb.png)

**Comment by paulakeen** [comment]
Consider specialising Role from the W3C org:Role class:

![role](https://user-images.githubusercontent.com/16134316/79694883-93c17300-8273-11ea-8e5c-690f1b711e13.png)

**Comment by janbmgo** [comment]
I have to study the details of the proposal yet a first point that strikes me is that in contrast with ISA Core Voc v 1.00 you put "an identifier" in the Agent class, whereas the v 1 puts it independent both of the person (natural person) and  the legal entity classes. The latter choice can be aligned with different situations. For instance in Belgium, identifiers for person are different from those of legal entities (is VAT nr, which also exist for public organisations); in other countries a TIN may be an identifier that is common for both categories.  

A second concern is the distinction that EIRA Organisational View makes between the provider of public services (public organisation) and the "Public service delivery agent".  This situation is common, the so-called public private partnerships in the delivery of public services. In the current core vocabularies such situation isn't clearly addressed. A possible topic for the conflation? Or is topic already addressed somehow?

**Comment by aidig** [comment]
A more coherent and consistent view upon the interrelationship between the core vocabularies would be great indeed. 

However, it might be best achieved by ensuring that whenever possible the vocabularies reuse classes and properties from each other or reuse the same classes and properties from external sources. Furthermore, a coherent overview might be possible by way of creating a profile rather than replicating classes such as org:organization in cagv:Organisation or rov:RegisteredOrganization in cagv:RegisteredOrganisation. It is however, somewhat difficult to evaluate the semantic similarity without access to the definitions of the proposed subclasses.
 
Generally, as advised in ISA2 RDF guides, when creating vocabularies, the process involves researching existing terms and their usage and _maximising re-use_ of those terms. Where new elements can be seen as specialisations of existing elements, the recommendation is to create sub classes and sub properties as appropriate, however, if the semantics of an element in an existing vocabulary is the same and the implications presented in the existing vocabulary do not restrict the reuse of a given element, it is important to build on and not replicate identical elements. A certain level of confidence in vocabulary publishing organisation is necessary of course.
 
A person, a public organisation, a business and an IT system are all able to take the role of Agent. 
Specifically, person, organisation and IT system are semantically disjoint / mutually exclusive and carry several domain specific properties calling for designated core vocabularies.
However, the metadata required for describing (registered) public organisations and businesses seem to overlap to a greater extent, so it would make sense to align the metadata and use the same properties across these classes.

Comment provided by: 
https://github.com/aidig
https://github.com/pebran
https://github.com/mayaborges

**Comment by paulakeen** [comment]
This relates to another proposal to SEMIC, OP an other organisations about the need of defining a Core Agent Vocabulary that clarifies/disambiguates these relations.

In this vocabulary, the design of a pattern for role is crucial and not trivial. In [ePO](https://github.com/eprocurementontology/eprocurementontology/wiki), for example, we treat with one single organisation (normally a public administration) that play different roles depending of the particular "situation" in which the agent(s) is/are involved.

**Comment by augusto-herrmann** [comment]
I agree with the input provided by @aidig, @pebran and @mayaborges.

Furthermore, I have some considerations with regards to the proposed model. This proposed "Agent" that could be a Person, Organization, etc., would be an [Anti-Rigid](https://ontouml.readthedocs.io/en/latest/theory/rigidity.html#rigidity) type, because it is not necessarily an agent during the entirety of its lifespan. Agent also does not provide [identity](https://ontouml.readthedocs.io/en/latest/theory/identity.html), as it is a type that can represent many different kinds of things. In [OntoUML](https://ontouml.org/) terms, Agent seems to be a [RoleMixin](https://ontouml.readthedocs.io/en/latest/classes/nonsortals/rolemixin/index.html#rolemixin).

The example of a RoleMixin on that page is even an Agent class:

![ontouml_rolemixin-application-2](https://user-images.githubusercontent.com/1058414/129793210-2c719c08-59ac-4c7c-a8d7-b6627cf81945.png)

Since RoleMixins do not provide identity and can be of transient nature, I'm not sure they are well suited to be the center piece of an ontology or vocabulary. What if a person was not previously an Agent, then becomes an Agent, then ceases to be one once again? Does it make sense to set the id attribute on this class which does not provide identity? The anti-rigid non-sortal characteristic of Agent makes me think that perhaps it could be represented in RDF as blank nodes, which do not have identity? I'm not sure.

Besides, people who intend to represent public organizations are hardly going to find and use this vocabulary if it is named "Core Agent Vocabulary". So "Core Public Organization Vocabulary" seems to make more sense for findability as it is a lot more domain-specific. Perhaps if the model is kept centered around those concepts and Agent is included as a peripheral thing it would help people find and use it more.

On the other hand, I agree that in some contexts and use cases it might be easier to use just a single vocabulary instead of several. But other use cases might not require them all.

**Comment by makxdekkers** [comment]
I'd like to comment on this statement from @augusto-herrmann : 

_What if a person was not previously an Agent, then becomes an Agent, then ceases to be one once again?_

As far as I understand, there is no choice for a Person to be sometimes an Agent and sometimes not: if the class Person is defined as a subclass of the class Agent, a Person is always an Agent.

**Comment by augusto-herrmann** [comment]
> As far as I understand, there is no choice for a Person to be sometimes an Agent and sometimes not: if the class Person is defined as a subclass of the class Agent, a Person is always an Agent.

That is precisely my point. If there is any possible situation that a Person might not be an Agent, then a model that defines the class Person as a subclass of the class Agent is necessarily wrong. I'm not saying that is the case, but rather raising the question.

**Comment by makxdekkers** [comment]
@augusto-herrmann I understand, but in this case there is no possible situation that a Person might not be an Agent because the class Person is defined as a subclass of Agent. Being a Person implies you are an Agent, always, by definition.

**Comment by augusto-herrmann** [comment]
Yes, @makxdekkers, I understand that. It has always been clear that defining Person as a subclass of Agent makes it so that being a Person implies that you are an Agent.

It is possible to build any model within the constraints of the language it uses. However, not every model can pass as a representation of the real world. What I'm asking is if this model, defined as is, can be interpreted as representation of real world situations. If Agent is interpreted as a role, one could admit possible real world situations where a Person does not fulfill that role. Therefore any modeling that would define Person as a subclass of Agent would necessarily be wrong.

The modeling must represent the real world and not the other way around. The question is: is Agent a role? If not, why not?

**Comment by makxdekkers** [comment]
@augusto-herrmann one important aspect is to keep in mind what the definition is of Agent in the context of Core Vocabularies and in the wider RDF world. It is not just what someone might think the meaning of 'agent' is.
So in FOAF, the definition is "_An agent (eg. person, group, software or physical artifact)_"; not entirely satisfactory as a definition as it is quite circular but gives some examples. The DCMI definition is a bit clearer: "_a resource that acts or has the power to act_". So, in my mind, Agent is an entity that is **able** to act (which is a innate characteristic), and not just an entity that is acting at any particular point in time (which would make it a role).

**Comment by augusto-herrmann** [comment]
Are you sure a Person is always **able** to act? What about a *deceased* Person? I still think of Agent as a [role](https://ontouml.readthedocs.io/en/latest/classes/sortals/role/index.html), that could be represented either by a relationship property or a node (so that the relationship itself can have properties), like this:

![person-agent](https://user-images.githubusercontent.com/1058414/130234232-a06e28c8-12b0-4e47-9a2f-6f3d7da864c0.png)

A *role* is specifically forbidden to be a supertype of a rigid type, as explained [here](https://ontouml.readthedocs.io/en/latest/classes/sortals/role/index.html#constraints):

> **C3:** A «Role» cannot be a supertype of a rigid type («Kind», «Subkind», «Collective», «Quantity», «Relator», «Category»).
> 
> ![ontouml_role-forbidden-2](https://user-images.githubusercontent.com/1058414/130234501-37536a70-d845-4a21-9801-c11b19a01fbb.png)

Which is *exactly* what happens when you define Agent as a supertype of Person.

**Comment by augusto-herrmann** [comment]
I should also mention that, because of the first constraint,

> **C1:** A «[Role](https://ontouml.readthedocs.io/en/latest/classes/sortals/role/index.html#role)» must always have **exactly** one [identity provider](https://ontouml.readthedocs.io/en/latest/theory/identity.html#identity) («Kind», «Collective», «Quantity», «Relator», «Mode», «Quantity») as an ancestor (a direct or indirect super-type). To model our list of roles presented above, we should given them identity providers:
> 
> ![ontouml_role-application-1](https://user-images.githubusercontent.com/1058414/130236711-d75f2dfa-187c-4554-8a65-09bd992ba8a8.png)

a role cannot have two identity providers (i.e. Person **and** Organisation). If we want an Agent to be both, it could only work as a «RoleMixin», as I mentioned previously, and modeled below:

![agent-rolemixin](https://user-images.githubusercontent.com/1058414/130237744-c459a589-91f3-405c-a3df-3a761b417494.png)

**Comment by makxdekkers** [comment]
@augusto-herrmann As far as I am aware,  the class Agent (as defined by [FOAF](http://xmlns.com/foaf/spec/#term_Agent), [DCMI ](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Agent), [PROV-O](https://www.w3.org/ns/prov#Agent) and [Wikidata](https://www.wikidata.org/wiki/Q24229398), but also [elsewhere](https://lov.linkeddata.es/dataset/lov/terms?q=Agent&type=class)) was specifically created to be the superclass of things like persons, organizations, groups, bots, to be used as a generalization in places where you need to express that someone or something is/was responsible of something happening. This is its intention and this is how if is very widely used. In that sense, it appears to satisfy a need.
Whether or not a person or organisation is **always** able to act is not relevant -- the class Agent is explicitly defined to be the superclass of those other, more specific classes. In a way, FOAF could have called the class `foaf:PersonOrOrganizationOrGroupOrBot` instead of `foaf:Agent` and it would have served the same purpose -- at least the shorter label makes it easier to talk about it.

**Comment by augusto-herrmann** [comment]
> Whether or not a person or organisation is always able to act is not relevant -- the class Agent is explicitly defined to be the superclass of those other, more specific classes. In a way, FOAF could have called the class foaf:PersonOrOrganizationOrGroupOrBot instead of foaf:Agent and it would have served the same purpose -- at least the shorter label makes it easier to talk about it.

So you now say that the definition of `foaf:Agent` is devoid of semantics, in what one would normally think of an Agent, as being **able** to act. That it's just an amalgamation of those aforementioned classes (which would probably make it a [Category](https://ontouml.readthedocs.io/en/latest/classes/nonsortals/category/index.html)).

Considering that, this is precisely the reason not to reuse this specific class, and to use instead the [RoleMixin pattern](https://ontouml.readthedocs.io/en/latest/patterns/rolemixin/index.html) as I suggested above. We could subclass `org:Organisation` and `foaf:Person`, but define our own `cagv:Agent` with no direct relation to `foaf:Agent`. Specifically not being a subclass of it.

![agent-rolemixin-with-imports](https://user-images.githubusercontent.com/1058414/130723864-164be09c-9c07-4682-bb22-1d5d362c5e0a.png)

That way, `cagv:Agent` *could* carry the semantics of being *able to act*, and not be an innate, present in every possible world, characteristic of persons (even dead) or organisations (even extinct) – and having a sound conceptual model at the same time.

**Comment by makxdekkers** [comment]
@augusto-herrmann I did not say that `foaf:Agent` is devoid of semantics. It is what it is, basically the union of a number of classes and it is being widely used in that sense.
Now if you are suggesting that we consider creating a class of our own that has different semantics, I would suggest not calling it Agent, but maybe something like Actor to avoid confusion.
However, I am not sure what the use case of this Actor class would be. It would be different from the use case that was brought up by @paulakeen as the subject of this issue, which was explicitly defined (in the diagram) as a subclass of `foaf:Agent`.

**Comment by GeertThijs** [comment]
@augusto-herrmann Same in CIDOC-CRM (ontology for CulturalHeritage): a Person is defined as an Actor (which is a concept a little bit smaller than an Agent). It is defined as a Thing as well (via BiologicalObject -> PhysicalObject -> PhysicalThing). Which corresponds to the FOAF and DCTERMS definitions: "A resource that acts or has the power to act." and "An agent (eg. person, group, software or physical artifact)." and "Things that do stuff". I agree with @makxdekkers that it is more a capability than a continuous state. And that it is more an abstract superclass for similar classes like Person, Organization, Software..., useful but not essential to the CPV, CPOV and CBV which each focus on their actual domain being Person and (Public) Organization. By the way: interesting thing this OntoUML, I will take a look into that.

**Comment by GeertThijs** [comment]
@paulakeen I am not sure that it would be a good thing to conflate CPV, CPOV and CBV as Agent is a broader concept than Person or Organisation (Software, Robots etc are also Agents). Its not that Agent is the actual concern of mentioned vocabularies. Conflating CPOV en CBV would be a better idea though. It is something we tried with our semantic [OSLO-standards](https://overheid.vlaanderen.be/oslo-wat-is-oslo). We combined [W3Corg](https://www.w3.org/TR/vocab-org/) (=successor of CBV if I am correct) with [CPOV](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/core-public-organisation-vocabulary) and with [REGORG ](https://www.w3.org/TR/vocab-regorg/) for RegisteredOrganizations in [one application profile](https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/). But I agree with @aidig that in many cases it is sufficient to reuse an existing concept without absorbing the entire vocabulary it originates from. Isn't that just the whole idea of the knowledge graph on the web where you jump from domain to domain according to your needs in stead of centralizing all knowledge in one model?

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to create just a consolidated diagram which has been published at:
https://github.com/SEMICeu/Core-Person-Vocabulary/tree/master/releases/2.00
