### ISSUE TITLE
Adaption of the gender for intersex and/or transgender people

### ISSUE THREAD

**Issue by ghost** [SEMICeu/Core-Person-Vocabulary#7]
### copied text from other issue (https://github.com/european-commission-europass/Europass-Learning-Model/issues/30)

**Describe the organisation you represent**
The [GWDG](https://www.gwdg.de), an organization related to the University of Göttingen and the Max-Planck institute. 
Currently working together with other universities to implement a platform for international student mobility.

**Specify the *nature* of your comment**
Choose *labels* from the right hand side to categorise your comment. Feedback types include:

* a suggested change or adjustment 

**Free text comment**
The [edci_mdr_humansex.xsd](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/XSD/imported/edci_mdr_humansex.xsd) contains two possible values for the human sex. However, in reality intersex people neither fit into these models.

As a solution to this, we in Germany have four different possible values for the *Personenstand* (vital record): male, female, diverse, empty value.

In order to align the data model with the national conventions, I suppose two different changes:

1. Extend the `edci_mdr_humansex.xsd` enumeration by two more values.
2. Remove all references to the human sex.

Personally I'd like to see the second change, as it would make the data model also more friendly to transgender people. Yes, this is very subjective, **but in my opinion there's absolutely no need for the sex/gender in the data model**. The combination from name and ID should provide enough relevant information.

---

### additional notes
I've got redirected towards this repo (see linked issue above), therefore I simply copied the text, since this seems to belong to the sex/gender markers in the *Core Person Vocabulary*. I could not find the file itself where the sex/gender markers are defined, otherwise I'd have linked it.

edit: after a quick skim through the document (https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Location_Person-Specification-v1.00.docx), it seems that the sex/gender vocabularies are mixed together, there does not seem a clear indicator about what is what. As I mentioned above, **there's absolutely no need for the sex/gender in the data model**, since each definition would not fully cover the reality of the people.

**Comment by EmidioStani** [comment]
The core person vocabulary enlist possible properties to describe a person, such properties are optionals 

The list you are referring is maintained by the Publications office see https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/human-sex/?target=Browse&uri=http://publications.europa.eu/resource/authority/human-sex which contains 4 values, discussion should be brought over there

**Comment by frank-steimke** [comment]
The KoSIT can confirm that Germany introduced the gender "divers" in several national code lists and that for a proper mapping from and to EU changes to the Publications Office lists should be made.

**Comment by mayaborges** [comment]
There is a risk here of confusing sex (biology) and gender (identity). For instance ‘intersex’ refers to a sex. Unfortunately, the usage note for gender suggests the the property can be used for both sex and gender, while the definition itself adds no meaning besides the term. 
By using one property to mean two distinct things interoperability is lost. In this case specifically it introduces a risk of errors, where sex may end up being read as gender, something that can be very hurtful to people for whom the two are not the same. Therefore the property should be specified to only cover gender. If there is a need to know a person’s biological sex a separate property would be needed. However, it’s hard to see a legimate use for this outside of the health care sector, so it may not be appropriate to include it in a core vocabulary, which may suggest to some implementers that it should be included. 
And, yes, the options for gender should - at a minimum - include ‘diverse’.

**Comment by frank-steimke** [comment]
Yes. The description in Core Vocabulary reads _"The gender of an individual should be recorded using a controlled vocabulary that is appropriate for the specific context. In some cases the chromosomal or physical state of an individual will be
more important than the gender that they express, in others the reverse will be true."_

So i think that the core vocabulary is capable to cover sex as well as gender. The precise semantic depends on the use of this Core Vocabulary Attribute in the specific context.

We are especially interested in the use of this attribute in case of eIDAS tokens. The eIDAS attribute set for natural person includes gender and refers to the Core Vocabulary attribute, see _"eIDAS SAML Attribute Profile 1.2, August 2019"_. The value of this attribute is usually set at birth and will often remain unchanged, however can be changed based on official decisions. I am not sure whether this is biology or identity, because there may be cases where the identity claimed by the person itself differs from the value that we find on the identity card.  Maybe the semantic of the property gender in this particular case would be something like "the value for the persons gender that has been assigned by the responible body".

**Comment by mayaborges** [comment]
A controlled vocabulary may simply contain the values 'male, female' or even 'male, female, diverse', which give no information as to whether we are dealing with gender or sex. 

Maybe what we really need is the property 'legal gender' (A person's gender as represented or recognized in any of various legal systems) as defined in Gender, Sex, and Sexual Orientation Ontology (https://bioportal.bioontology.org/ontologies/GSSO)

**Comment by EmidioStani** [comment]
The definition of gender has been updated together with other entities: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
