### ISSUE TITLE
Date or DateTime

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Person-Vocabulary#9]
Within [WP4 of the SDG](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/birth_certificate/data_model/birth_certificate_tables.md#child), it was decided to use the Date datatype instead of the DateTime datatype as currently used by Core Person for the date of birth property, because the first is not always available. This is also more in line with `schema:birthDate`, the URI that is being reused by the Core Vocabulary.

Does everyone agree to change the range of dateOfBirth and dateOfDeath to `xsd:Date`?

**Comment by giorgialodi** [comment]
Yes I agree! if it is dateOfBirth and dateOfDeath it should be xsd:date :)

**Comment by SebastianSK** [comment]
I do not agree that dateOfBirth is suffently expressed using a xsd:date. 
For more then a decade now in Germany we have composed data types regarding the birthDate. I raised an own ticket for this
https://github.com/SEMICeu/Core-Person-Vocabulary/issues/17

**Comment by giorgialodi** [comment]
Ok @SebastianSK in that issue I see different requirements and then you are right, we need to take them into account in the modelling. Probably we need to have a concept like TemporalEntity that can be then specialized in different way: it can be a Year, Month, TimeInstant (a date or dateTime) or other;  also the TemporalEntity can have a property that is text that allows anyone to put whatever, in those exceptional cases. Another possibility is to have in the core voc just a general concept of TemporalEntity so that MSs can extend it to accommodate the different scenarios they have to deal with. Probably dateOfBirth in this case is not appropriate as that name of the property reminds an exact date. And we may also include both: an exact date (to simplify queries) and some more complex modelling to meet the requirements you mentioned.

my2cents

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, participants agreed to use `xsd:date` as the data type for the date of birth/death, together with a clear recommendation in the usage note of the property on how to handle specific cases, such as when part or the entire date is unknown as raised in issue #17.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to create a datatype Date as union of xs:date, xs:gYearMonth and xs:gYear,

**Comment by EmidioStani** [comment]
The consolidated diagram: https://github.com/SEMICeu/Core-Person-Vocabulary/blob/master/releases/2.00/ISA_Core_Vocabularies_2.00.EAP includes the new data type
